eiffel-community/eiffel-intelligence

- .travis.yml
- LICENSE
- README.md
- pom.xml
> EI in GITHUB

- .gitignore
- pom.xml
- src/main/java/com/ericsson/ei/App.java
.gitignore, pom updated & bugfix in main if arg is null
> .gitignore, pom updated & bugfix in main if arg is null

- pom.xml
> groupId updated

- src/main/java/com/ericsson/ei/erqueryservice/ERQueryService.java
Hi @emichaf 
I'm not sure how to link the issue in the title so here it is: [#39](https://github.com/Ericsson/eiffel-intelligence/issues/39)
> Make ERQueryService operations safe

- pom.xml
- src/main/resources/TestSourceChangeObjectRules.json
- src/test/resources/TestSourceChangeObjectRules.json
- src/test/resources/aggregatedSourceChangeObject.json
SC rulesupdated. POM updated for tomcat  <scope>compile</scope>, so compile and debug can be started from editor.
> SC rulesupdated. POM updated for tomcat

- src/main/java/com/ericsson/ei/queryservice/ProcessAggregatedObject.java
- src/test/java/com/ericsson/ei/queryservice/test/QueryServiceTest.java
1. The query modified id to _id
2. updated related test cases
> Modified query for aggregated objects id to _id

- src/main/java/com/ericsson/ei/subscriptionhandler/SubscriptionValidator.java
- src/test/java/com/ericsson/ei/subscriptionhandler/test/SubscriptionValidatorTest.java
Subscription validation updated for MAIL
> Subscription validation updated for MAIL

- pom.xml
> Bumped lombok version

- pom.xml
pom updated, libs version bumped
> pom updated

- src/functionaltests/java/com/ericsson/ei/scaling/ScalingAndFailoverSteps.java
- src/functionaltests/java/com/ericsson/ei/utils/EventManager.java
- src/functionaltests/resources/features/scalingAndFailover.feature
- src/test/java/com/ericsson/ei/flowtests/FlowTestBase.java
This pull request should have concerened following commits as well:
f8d576786a3eb10874ace71c33edd4f2e82d6124
5d1c3838003d5b4f388c8442d1aabf050797b7ff
These were accidentally merged in with the master branch along with some other commit history...
> Mongo tear down, refactoring, clean up etc.

- docs/index.md
- src/main/java/com/ericsson/ei/rmqhandler/RmqHandler.java
- src/test/java/com/ericsson/ei/waitlist/TestWaitListWorker.java
Hi there,
I wrote this bot based on the top 10 most misspelled english words.
(https://blog.oxforddictionaries.com/2016/08/02/corpus-misspellings/)
The bot queries, forks, clones, fixes and commits but I manually create the PRs.
All the best,
Jimmy
> Fixed Spelling.

- src/functionaltests/java/com/ericsson/ei/query/QueryAggregatedObjectsTestSteps.java
- src/functionaltests/resources/features/queryAggregatedObjects.feature
- src/functionaltests/resources/queryAggregatedObject7.json
- src/main/java/com/ericsson/ei/mongodbhandler/MongoDBHandler.java
- Added a test to verify that it is possible to get the latest sucessfull
confidence level for a specific commit.
We can now show that it is possible to get the latest sucessfull
confidence level for a specific **commit.** …
> Add test for query confidence levels

- src/functionaltests/java/com/ericsson/ei/notifications/ttl/TestTTLSteps.java
- src/functionaltests/resources/features/ttl.feature
- src/functionaltests/resources/subscription_single_ttlTest.json
- src/main/java/com/ericsson/ei/handlers/DateUtils.java
- src/main/java/com/ericsson/ei/handlers/ObjectHandler.java
- src/main/java/com/ericsson/ei/subscriptionhandler/InformSubscription.java
- src/test/java/com/ericsson/ei/queryservice/test/QueryServiceTest.java
> Functional Test for ttl and time indexing added to docs before inserting into mongoDB

- src/main/java/com/ericsson/ei/jmespath/JmesPathInterface.java
fix nullpointer exception
Null object returned when rule run on event
null object returned from JmesPathInterface replaced with valid empty json object to avoid nullpointer exception
none
Avoid null pointer exception
none
permitted to submit under …
> fix nullpointer exception

- src/main/java/com/ericsson/ei/handlers/HistoryExtractionHandler.java
- src/main/java/com/ericsson/ei/handlers/ObjectHandler.java
- src/main/java/com/ericsson/ei/jmespath/JmesPathInterface.java
- src/main/java/com/ericsson/ei/jsonmerge/MergePrepare.java
- src/main/java/com/ericsson/ei/mongodbhandler/MongoDBHandler.java
Avoid exceptions
Refactoring to avoid exceptions
None
less exceptions
None …
> some refactoring

- src/main/java/com/ericsson/ei/handlers/UpStreamEventsHandler.java
- src/main/java/com/ericsson/ei/jmespath/JmesPathInterface.java
- src/test/java/com/ericsson/ei/jmespath/test/TestJmesPathInterface.java
We get null pointer when receiving empty array from upstream requests from Event Repository
Add check for null value
Check that array is null
Avoid null pointer exception when empty array retrieved from Event Repository
None …
> refactoring and null pointer fix

- pom.xml
Step version of jackson-databind to 2.9.5
vulnerability issues reported with jackson-databind version between version of jackson-databind from 2.9.0 to 2.9.4. 
Step version of jackson-databind to 2.9.5
None
Avoid security vulnerabilities
None …
> Step version of jackson-databind to 2.9.5

- src/main/resources/application.properties
- src/test/java/com/ericsson/ei/erqueryservice/test/ERQueryServiceTest.java
URL for ER in property file and in test file was not correct.
Corrected the URL.
None
EI can connect to ER now.
None
(c) The contribution was provided directly to me by …
> Updated ER's URL in property file and test file

- src/functionaltests/java/com/ericsson/ei/subscriptions/repeatHandler/SubscriptionRepeatHandlerSteps.java
- src/functionaltests/resources/features/queryAggregatedObjects.feature
- src/functionaltests/resources/features/ruleCheck.feature
- src/functionaltests/resources/features/subscriptionBulk.feature
- src/functionaltests/resources/features/subscriptionCRUD.feature
- src/functionaltests/resources/features/subscriptionRepeatHandler.feature
Previously each test scenario in the functional test feature file were not able to run individually.
Added tags on test scenarios in feature files.
By adding tags to each scenario it is now possible to run scenarios individually or in combination with others. …
> Add test tags in functional tests

- src/functionaltests/resources/queryAggregatedObject5.json
- src/main/resources/ArtifactRules_new.json
- src/test/java/com/ericsson/ei/jmespath/test/TestIncompleteJmesPathFilter.java
- src/test/resources/AggregatedDocumentInternalCompositionLatest.json
- src/test/resources/ArtifactRules_new.json
- src/test/resources/RulesHandlerOutput.json
- src/test/resources/test_events.json
Today we only aggregate svnIdentifier from SCM in Artifact rules. We need to change this to gitIdentifier. We also need to aggregate gitIdentifier from SCC in Artifact rules.
This will also require that some events used in flow test have to be updated and also the expected data from aggregated object. …
> Fix aggregate git identifier rules

- src/main/resources/application.properties
Improve comments application properties file. 
Clarify time unit for TTL, add recommended settings for some TTL values.
None
Hopefully more clear for users the TTL settings in application properties.
None
permitted to submit under a different …
> Add more comments to application properties file

- src/main/java/com/ericsson/ei/handlers/UpStreamEventsHandler.java
In traverseTree (UpStreamEventsHandler), getRulesForEvent returned
null if it couldn't find any rule, this fix makes
sure it doesn't happen if it can't find any rule
(c) …
> Fix NullPointerException from runHistoryExtraction

- README.md
- wiki/Query.md
Update documentation
Added example of the query that returns all aggregated objects.
Better documentation …
> Add query example that returns all aggregated objects

- src/main/java/com/ericsson/ei/controller/model/ParseInstanceInfoEI.java
Added rules path so it may be displayed on the EI front end information page if applicable.
person who …
> Added rules path

- src/main/resources/templates/subscriptionsTemplate.json
Added all elements in that is in the subscription file. There may be elements like notificationMessageKeyValuesAuth that maybe should be deleted from subscriptions but are there now in live subscriptions.
permitted to submit under a different …
> Updated subscription templates file

- src/main/java/com/ericsson/ei/subscriptionhandler/InformSubscription.java
* If the field "userName" or "password" did not exist while auth type
was set as "BASIC_AUTH", a null pointer exception occured. This change  
will fix that.
(c) The …
> Fix null pointer exception in InformSubscription

- src/functionaltests/resources/subscription_multiple.json
- src/main/java/com/ericsson/ei/subscriptionhandler/InformSubscription.java
- src/main/java/com/ericsson/ei/subscriptionhandler/SubscriptionHandler.java
When an object has been aggregated we loop through subscriptions in a separate thread to check them against the aggregated object. I a subscription check fails with an exception the thread is terminated and all the remaining subscriptions will not be checked.
Move the check of the subscription's conditions in a try catch loop that will log an error that the subscription failed but the thread will not be terminated.
None
All the subscriptions will be checked always.
None
of my …
> improve exception handling in subscritption handler

- README.md
- wiki/markdown/Authentication.md
- wiki/markdown/Email-notification.md
- wiki/markdown/REST-POST-notification.md
- wiki/markdown/Subscriptions.md
- wiki/markdown/index.md
- wiki/markdown/subscription-with-REST-POST-notification.md
- wiki/markdown/subscription-with-email-notification.md
- wiki/site.xml
Enabling LDAP has consequences for subscriptions but no information about it could be find in the documentation.
Information about how LDAP affects subscription ownership was added. Describing which CRUD operations can be performed on subscription when LDAP is activated.
Also restructured the Subscription section of the user documentation. Renamed two files and updated the subscription examples with up-to-date template subscriptions. Added comments where needed.
Corrected some minor misspellings and changed wordings in a few places.
Up to date and accurate user documentation about subscription and how they are impacted when LDAP is activated in EI.
(a) The contribution was created in whole or …
> Add LDAP information in user documentation

- .travis.yml
Travis outputs too much logs.
This change should remove some of those logs.
person who certified (a), (b) …
> Remove mvn logs

- src/main/java/com/ericsson/ei/controller/SubscriptionControllerImpl.java
- src/main/java/com/ericsson/ei/services/SubscriptionService.java
Removed stack trace from info logging when subscriptions where not found. …
> Removed stack trace from info logging when subscriptions where not found.

- README.md
- src/test/resources/SourceChangeObjectRules.json
- src/test/resources/TestSourceChangeObject.json
- src/test/resources/aggregatedSourceChangeObject.json
Change-Id: I7978d3b6fe6f08dc6f570f7d8eee6fe337ed4988
Example rules for Source Change aggregation were aggregating svnIdentifier.
Change rules for Source Change aggregation to aggregate gitIdentifier instead.
None
Rules in sync with most common SCM.
People need to modify the rules if using other SCMs than git.
work with modifications, whether created in whole or …
> replace aggregation of scm data

- src/main/resources/SourceChangeObjectRules.json
Source change aggregates the svnIdentifier instead of gitIdentifier. This have been fixed in the test file but not in the main one.
Aggregate gitIdentifier instead of svnIdentifier in the main file for source change rules.
None
Aggregation with content relevant to most users.
None.
by me, under the …
> Missed to update the main rule for source change

- docker-compose.yml
Removed url from docker-compose file.
it.
(d) …
> Remove URL from docker-compose file

- src/functionaltests/java/com/ericsson/ei/subscriptions/authentication/AuthenticationSteps.java
- src/functionaltests/java/com/ericsson/ei/subscriptions/repeatHandler/SubscriptionRepeatHandlerSteps.java
We were using annotations in cucumber scenarios which will become depreacted in the next version.
Changed to the new annotation standard.
Up-to-date cucumber code.
(c) …
> Updated cucumber annotations

- .travis.yml
- docker-compose.yml
- src/main/docker/docker-compose.yml
Stepping component versions to latest versions in docker-compose files. …
> Stepped component versions in docker-compose files.

- pom.xml
- src/functionaltests/java/com/ericsson/ei/utils/AMQPBrokerManager.java
- src/functionaltests/java/com/ericsson/ei/utils/TestConfigs.java
- src/functionaltests/resources/configs/qpidConfig.json
- src/main/java/com/ericsson/ei/services/SubscriptionService.java
- src/test/java/com/ericsson/ei/controller/TestQueryControllerImpl.java
- src/test/java/com/ericsson/ei/flowtests/AMQPBrokerManager.java
- src/test/java/com/ericsson/ei/queryservice/test/TestProcessQueryParams.java
- src/test/resources/configs/qpidConfig.json
Stepping Qpid version to resolve "potential security vulnerability" of the currently use qpid version. …
> Step Qpid version

- pom.xml
- src/integrationtests/java/com/ericsson/ei/integrationtests/FlowStepsIT.java
- src/integrationtests/resources/features/ArtifactFlowIT.feature
- src/main/java/com/ericsson/ei/subscriptionhandler/SubscriptionValidator.java
closes #263 
- Fix single notification issue so that multiple notification metas are
now accepted on the backend.
- Updated tests to test this.
- Updated lombok version. The current version didnt seem to work with openJDK. …
> Fix single notification meta issue

- pom.xml
- src/main/java/com/ericsson/ei/App.java
- src/main/java/com/ericsson/ei/mongodbhandler/MongoDBHandler.java
- src/main/java/com/ericsson/ei/waitlist/WaitListWorker.java
- src/main/resources/application.properties
It has been issues with stopping EI instances in Tomcat installations.
EI pom file and spring-boot-maven-plugin has been updated with a configuration change to solve the issue.
in the …
> Fixed stopping EI instances in Tomcat issue.

- wiki/markdown/artifact-created-event-aggregation.md
- wiki/markdown/artifact-published-event-aggregation.md
- wiki/markdown/confidence-level-modified-event-aggregation.md
- wiki/markdown/history-rules.md
- wiki/markdown/query.md
- wiki/markdown/running-rules-on-objects.md
- wiki/markdown/step-by-step-subscription-notification.md
- wiki/markdown/subscription-API.md
- wiki/markdown/subscription-with-REST-POST-notification.md
- wiki/markdown/subscription-with-email-notification.md
- wiki/markdown/test-case-finished-event-aggregation.md
- wiki/markdown/test-case-started-event-aggregation.md
- wiki/markdown/test-case-triggered-event-aggregation.md
- wiki/markdown/triggering-jenkins-jobs.md
-
Update documentation examples with purl identifier
-
-
-
person who certified (a), (b) or (c) and I have …
> Agen update to documentation examples

- src/functionaltests/java/com/ericsson/ei/notifications/ttl/TestTTLSteps.java
- src/functionaltests/java/com/ericsson/ei/subscriptions/repeatHandler/SubscriptionRepeatHandlerSteps.java
- src/main/java/com/ericsson/ei/config/ConfigurationValidator.java
- src/main/java/com/ericsson/ei/controller/SubscriptionControllerImpl.java
- src/main/java/com/ericsson/ei/controller/model/ParseInstanceInfoEI.java
- src/main/java/com/ericsson/ei/handlers/ObjectHandler.java
- src/main/java/com/ericsson/ei/subscription/InformSubscriber.java
- src/main/java/com/ericsson/ei/subscription/RunSubscription.java
- src/main/java/com/ericsson/ei/subscription/SendHttpRequest.java
- src/main/java/com/ericsson/ei/subscription/SendMail.java
- src/main/java/com/ericsson/ei/subscription/SubscriptionHandler.java
- src/main/java/com/ericsson/ei/subscription/SubscriptionRepeatDbHandler.java
- src/main/java/com/ericsson/ei/subscription/SubscriptionValidator.java
- src/test/java/com/ericsson/ei/handlers/test/ObjectHandlerTest.java
- src/test/java/com/ericsson/ei/services/SubscriptionRestAPITest.java
- src/test/java/com/ericsson/ei/services/SubscriptionServiceTest.java
- src/test/java/com/ericsson/ei/subscription/SubscriptionHandlerTest.java
- src/test/java/com/ericsson/ei/subscription/SubscriptionRepeatDbHandlerTest.java
- src/test/java/com/ericsson/ei/subscription/SubscriptionValidatorTest.java
Renamed some packages, class names and method names.
More readable code. …
> Refactoring class names

- src/main/java/com/ericsson/ei/subscription/SubscriptionValidator.java
- src/test/java/com/ericsson/ei/subscription/SubscriptionValidatorTest.java
> regEx changed in backend to match those in frontend

- pom.xml
- src/integrationtests/java/com/ericsson/ei/integrationtests/FlowStepsIT.java
- src/integrationtests/resources/features/ArtifactFlowIT.feature
- src/integrationtests/resources/features/SourceChangeFlowIT.feature
- src/integrationtests/resources/features/TestExecutionFlowIT.feature
- src/main/java/com/ericsson/ei/subscription/SubscriptionRepeatDbHandler.java
There was a security risk in jackson databind library.
Stepped the dependency to 2.9.9
Also updated some spelling mistakes I noticed when running the integration tests.
Less risk in dependencies
None that I can think of
permitted to submit under a …
> Stepped jackson databind version

- src/main/docker/docker-compose.yml
- src/main/resources/rules/ArtifactRules-Eiffel-Agen-Version.json
- src/main/resources/rules/ArtifactRules-Eiffel-Toulouse-Version.json
No issue. Just fulfilling some requests.
Extract custom data from ArtifactCreatedEvent
None
Custom data will be available for use.
Too much data :)
(c) The contribution …
> extend artifact rules with custom data

- pom.xml
- src/main/java/com/ericsson/ei/controller/EIHomeController.java
Qpid has been started in normal EI applications exections. Qpid should only be used and started during tests. This change fixes this issue.
EI application root URL is now redirecting to Swagger Rest endpoints information page.  …
> Disable Qpid and redirect root url to swagger web page.

- src/main/java/com/ericsson/ei/controller/RuleController.java
- wiki/markdown/running-rules-on-objects.md
- Added rules endpoint documentation to the wiki docs.
person who certified (a), (b) or (c) and I have not …
> Add rules endpoint to documentation

- pom.xml
- Fix jackson-databind security alert, 2.9.9 -> 2.9.9.1
person who certified (a), (b) or (c) and I have not …
> Fix jackson-databind security alert

- wiki/markdown/subscriptions.md
#311 
- Repeat handling was not described in backend. Added a link to information about it in the frontend. …
> Add repeat handling documentation

- src/main/java/com/ericsson/ei/handlers/DownstreamIdRulesHandler.java
- src/main/java/com/ericsson/ei/handlers/IdRulesHandler.java
- src/main/java/com/ericsson/ei/waitlist/WaitListStorageHandler.java
- src/test/java/com/ericsson/ei/waitlist/TestWaitListStorageHandler.java
Refactor the methods in WaitListStorageHandler
More readable and maintainable code
None.
person who …
> Refactor WaitListStorageHandler

- wiki/markdown/docker.md
- wiki/markdown/running-eiffel-intelligence.md
Adding some missing documentations.
it.
(d) I …
> Documentation improvements.

- .codacy.yaml
- .travis.yml
- README.md
- pom.xml
Previously, we did not use any code style or test coverage checks. 
* Enable Codacy 3rd party application for this repository. Codacy will analyze incoming pull reuqests and reject them if any new issues are introduced. 
* Include a .codacy.yaml file to limit code style checks for now. Currently I've ignored everything inside functional tests directory due to Codacy complaining about cucumber style methods being written with underscore '_'. This rule can be changed or we have to update the functional test method names to fit Java standard naming... Same goes for wiki/ directory. Codacy uses remark-lint which is very strict on list item indentation in markdown files. 
* Update README.md according to some issues found by Codacy.
* Add a badge to Codacy dashboard.
* Add maven cobertura …
> Enable codacy code style check

- src/main/java/com/ericsson/ei/config/HeaderAndCookieHttpSessionIdResolver.java
- There was a nullpointer occuring when running frontend
integrationtests. This was caused by trying to convert a attribute
to a string while it may sometimes be null. …
> Fix nullpointer bug in sessionID retrieval

- pom.xml
Vulnerabilities found in previous versions. See [CVE-2019-14540](https://nvd.nist.gov/vuln/detail/CVE-2019-14540) and [CVE-2019-16335](https://nvd.nist.gov/vuln/detail/CVE-2019-16335) for more details.
Stepped version of jackson-databind library. …
> Update jackson-databind to 2.9.10

- wiki/markdown/failed-notifications.md
Travis step deployGitHubPages wont pass without this fix.
person who certified (a), (b) or (c) and I have …
> Fix mvn site syntax error

- wiki/markdown/artifact-published-event-aggregation.md
> Removed old aggregateOject field from aggregatedObject example.

- pom.xml
- src/main/java/com/ericsson/ei/EndpointSecurity.java
- src/main/java/com/ericsson/ei/exception/AbortExecutionException.java
> Fixed the jasypt empty password error when Ldap is enabled.

- src/functionaltests/java/com/ericsson/ei/subscriptions/authentication/AuthenticationSteps.java
- src/main/java/com/ericsson/ei/EndpointSecurity.java
logout was still on /auth endpoint
/authentication/logout now works
person who certified (a), (b) or (c) …
> Fix auth to authentication for */logout

- src/main/docker/docker-compose.yml
- src/main/docker/jenkins/security.groovy
Closes https://github.com/eiffel-community/eiffel-intelligence/issues/383
A security groovy script has been added that explicitly creates the admin user.
(c) The …
> Add jenkins admin user script to container

- wiki/markdown/step-by-step-subscription-notification.md
- wiki/markdown/subscription-API.md
- wiki/markdown/subscription-with-REST-POST-notification.md
- wiki/markdown/subscription-with-email-notification.md
- wiki/markdown/subscriptions.md
- wiki/markdown/triggering-jenkins-jobs.md
The documentation about how to create subscriptions did not contain enough detailed examples in the JSON structures. It was also missing links to the front-end docs about calling the REST API.
* Extended the JSON examples of subscriptions of different notification types.
* Add json examples in text about subscription requirements and conditions
* Removed unused fields in subscription examples
* Rephrased some sentences to make the meaning clearer
* Update the subscription-API to include info about json format
Hopefully some additional examples will help first-time users to create subscriptions towards Eiffel Intelligence using the REST API.
(a) The contribution was created in whole or in part …
> Add examples in subscription docs

- src/integrationtests/java/com/ericsson/ei/integrationtests/flow/FlowStepsIT.java
- src/integrationtests/java/util/IntegrationTestBase.java
- src/test/java/com/ericsson/ei/flowtests/FlowTest.java
- src/test/resources/AggregatedDocumentInternalCompositionLatestIT.json
- src/test/resources/AggregatedDocumentInternalCompositionLatestUnitTest.json
Integration tests was often failing in travis.
Improved some checks in integration tests and ensured the possibility to count email.
Added timing between sending eiffel events since this could cause events not to be handled by IE.
permitted to …
> Improve reliability of integration tests

- pom.xml
There is mail dependency issue in classpath when it is executed in some specific environments and setups.
This pom file change will probably solve the issue.
(c) The …
> Fix mail dep issue.

- wiki/markdown/failed-notifications.md
The documentation for failed notifications API was a bit off.
Fixed the errors that I could find.
person …
> Fix to failed notifications documentation

- src/main/java/com/ericsson/ei/EndpointSecurity.java
Encryption check needed to be reversed.
it. …
> Fix encryption if statement

- .travis.yml
- README.md
- pom.xml
Random step of version
it.
(d) I understand …
> Step POM version

- wiki/markdown/REST-API.md
Capitalized text in REST-API.md
it.
(d) I …
> Fix text in docs

- wiki/configuration.md
- wiki/subscription-API.md
After the API for subscriptions was updated the documentation were missing some endpoints examples
- Add missing API description in table
- Rearranged order of GET and POST operations
- Add missing information about mongodb configurations
Easier to quickly understand how to use the endpoint
by me, …
> Update subscription API documentation

- pom.xml
- wiki/compatibility.md
> Updated compatibility charts for EI 3.0 version.

- pom.xml
- src/main/java/com/ericsson/ei/controller/AggregatedObjectControllerImpl.java
- src/main/java/com/ericsson/ei/controller/AuthenticationControllerImpl.java
- src/main/java/com/ericsson/ei/controller/FailedNotificationControllerImpl.java
- src/main/java/com/ericsson/ei/controller/InformationControllerImpl.java
- src/main/java/com/ericsson/ei/controller/RuleControllerImpl.java
- src/main/java/com/ericsson/ei/controller/RuleTestControllerImpl.java
- src/main/java/com/ericsson/ei/controller/StatusControllerImpl.java
- src/main/java/com/ericsson/ei/controller/SubscriptionControllerImpl.java
- src/main/java/com/ericsson/ei/controller/TemplateControllerImpl.java
- wiki/subscription-API.md
The Swagger interface contained some endpoints not aligned with the rest.
- Align description on endpoints
- Add clarification on subscription endpoint with single subscriptions
- Move tags declaration from class to methods to avoid generated clutter in Swagger gui
- Updated documentation about subscription API for 3.0.0
work with modifications, whether created …
> Improve swagger documentation

- wiki/subscription-with-email-notification.md
Fixes https://github.com/eiffel-community/eiffel-intelligence/issues/395
Provided the limitations and examples for notificationMessageKeyValues. Added some examples of subscription with mail notification with relevant information.
Easier for users to have concrete examples to look at when they write their own subscriptions.
work with modifications, whether …
> Added examples of subscription with email notification.

- pom.xml
We have a new vulnerability in EVMS about jackson-databind.
So I upgraded the jackson-databind version from 2.9.10.1 to 2.10.1 to remove the vulnerability.
Uplifted jackson-databind version to resolved security vulnerability issue.
permitted to …
> Uplifted jackson-databind version.

- .travis.yml
- pom.xml
- src/functionaltests/java/com/ericsson/ei/notifications/trigger/SubscriptionNotificationSteps.java
- src/functionaltests/resources/features/subscriptionNotification.feature
- src/main/resources/application.properties
Cobertura was having trouble with the split executions.
Switched to Jacoco instead to produce a coverage report.
(c) The contribution was provided directly to me by some …
> Codacy report fix

- wiki/subscriptions.md
Adding JMESPath link in subscription documentation
#399
person who certified (a), (b) or (c) and I have not …
> documentation update for subscription

- wiki/example-rules.md
Broken link discovered in #456 
Fix the relative path to the linked file.
Working links in the documentation :)
(c) The contribution was provided directly to me by some …
> Fix broken link in docs

- src/main/java/com/ericsson/ei/services/ISubscriptionService.java
- src/main/java/com/ericsson/ei/services/SubscriptionService.java
I noticed some duplicate logging happening when updating or deleting subscriptions in Eiffel Intelligence.
Add missing javadoc on some methods in SubscriptionService
Remove duplicate logging when updating and deleting subscriptions
Remove unneccessary if statement and unused imports
More readable code …
> Remove duplicate logging

- src/main/java/com/ericsson/ei/handlers/EventHandler.java
Closes #455 
Closes #454
The suggestions we had written in the issues was to properly resolve the port and trim away any extra port suffix from the thread name.
However, in this PR I simply remove the port since I'm not sure why it's logged in the first place. …
> 3.x Remove port logging in event handler

- src/main/java/com/ericsson/ei/handlers/EventHandler.java
The suggestions we had written in the issues was to properly resolve the port and trim away any extra port suffix from the thread name.
However, in this PR I simply remove the port since I'm not sure why it's logged in the first place.
permitted …
> 2.x Remove port logging in event handler

- pom.xml
Security issue with Junit 4.12
junit uplifted to version 4.13.1
Anders Breid
person who certified (a), (b) …
> 2.0.0-Maintanance - Bump junit from 4.12 to 4.13.1

- pom.xml
Uplifted the Httpclient version to 4.5.13. Tested the end to end functionality .Everything is working fine.
Secure from security vulnerabilities which was reported in EVMS tool.
in the …
> Uplifted the Httpclient version from 4.5.6 to 4.5.13

- .travis.yml
- src/functionaltests/java/com/ericsson/ei/notifications/ttl/TestTTLSteps.java
- src/functionaltests/java/com/ericsson/ei/rabbitmq/connection/RabbitMQTestConnectionSteps.java
- src/main/java/com/ericsson/ei/exception/MongoDBConnectionException.java
- src/main/java/com/ericsson/ei/handlers/DownstreamIdRulesHandler.java
- src/main/java/com/ericsson/ei/handlers/EventHandler.java
- src/main/java/com/ericsson/ei/handlers/EventToObjectMapHandler.java
- src/main/java/com/ericsson/ei/handlers/ExtractionHandler.java
- src/main/java/com/ericsson/ei/handlers/ObjectHandler.java
- src/main/java/com/ericsson/ei/handlers/RMQHandler.java
- src/main/java/com/ericsson/ei/jmespath/JmesPathInterface.java
- src/main/java/com/ericsson/ei/jsonmerge/MergeHandler.java
- src/main/java/com/ericsson/ei/mongo/MongoDBHandler.java
- src/main/java/com/ericsson/ei/notifications/InformSubscriber.java
- src/main/java/com/ericsson/ei/rules/IRuleTestService.java
- src/main/java/com/ericsson/ei/rules/IdRulesHandler.java
- src/main/java/com/ericsson/ei/rules/RuleTestService.java
- src/main/java/com/ericsson/ei/services/SubscriptionService.java
- src/main/java/com/ericsson/ei/utils/MongoDBMonitorThread.java
- src/main/java/com/ericsson/ei/waitlist/WaitListStorageHandler.java
- src/test/java/com/ericsson/ei/mongo/MongoDBHandlerTest.java
- wiki/REST-API.md
Added the changes from EI maintenance branch to master branch
Added the commits from EI backend maintenance branch to master branch.
These are the commits which were added:
https://github.com/eiffel-community/eiffel-intelligence/commit/bc766553f7b08dc84254b41facf420deb32e0c92
https://github.com/eiffel-community/eiffel-intelligence/commit/0637e9fc393a8f6a84870c4a9723625594a54907
https://github.com/eiffel-community/eiffel-intelligence/commit/5461175978de54dcc8ea5dd0a564ee838fd21460
https://github.com/eiffel-community/eiffel-intelligence/commit/6d1d5dd14fcf84b6d723714f15dc74642fc6c450
https://github.com/eiffel-community/eiffel-intelligence/commit/ce574ffe79d9ca11fd2b95d9673c2bae0e7e230a
https://github.com/eiffel-community/eiffel-intelligence/commit/36f94614a425cf10fb31a8283c4ac7e6744a20d0 …
> Merging EI maintenance branch to master branch

- pom.xml
Uplifted jackson databind from 2.10.1 to 2.12.1
This uplift has been done in order to prevent from security vulnerabilities.
(c) The contribution was provided directly to …
> Uplifted jackson databind from 2.10.1 to 2.12.1

- pom.xml
Eiffel Intelligence Version uplift for merging Maintenance branch to master
Now user can use the Eiffel Intelligence backend master branch. All the changes present in maintenance branch will be present in master
permitted to submit under a …
> Version uplift for merging EI maintenance to master branch

- pom.xml
NA
Fixed the Socket exception that occured while connecting to MongoDB. …
> Version release for Socket Exception fix.

- pom.xml
Updated version in pom file
it.
(d) I …
> Updated version in pom file

- pom.xml
- src/functionaltests/java/com/ericsson/ei/threadingAndWaitlistRepeat/ThreadingAndWaitlistRepeatSteps.java
- src/main/java/com/ericsson/ei/config/SpringAsyncConfig.java
- src/main/java/com/ericsson/ei/handlers/EventToObjectMapHandler.java
- src/main/java/com/ericsson/ei/handlers/ExtractionHandler.java
- src/main/java/com/ericsson/ei/handlers/MongoDBHandler.java
- src/main/java/com/ericsson/ei/handlers/ObjectHandler.java
- src/main/java/com/ericsson/ei/handlers/UpStreamEventsHandler.java
- src/main/java/com/ericsson/ei/jsonmerge/MergeHandler.java
- src/main/java/com/ericsson/ei/subscription/RunSubscription.java
- src/main/java/com/ericsson/ei/subscription/SubscriptionHandler.java
- src/main/java/com/ericsson/ei/subscription/SubscriptionRepeatDbHandler.java
- src/main/java/com/ericsson/ei/waitlist/WaitListStorageHandler.java
- src/main/resources/application.properties
- src/test/java/com/ericsson/ei/subscription/SubscriptionRepeatDbHandlerTest.java
Rejection handler
If the subscription handler pool overflows the events are lost. A rejection handler will force the overflowing calls to be run in the caller's thread instead, not to lose events.
Cache of subscription
In the subscription handler, we cache the subscriptions avoiding calling the database to see if the subscription was triggered or not already
Remove duplicate call to subscription handler
In the current code we make two calls to the subscription handler. We only need to do one
(b) The contribution is based upon previous work that, to …
> 2.0.0 maintenance

- pom.xml
- src/main/java/com/ericsson/ei/handlers/EventToObjectMapHandler.java
- src/main/java/com/ericsson/ei/handlers/ObjectHandler.java
- src/main/java/com/ericsson/ei/handlers/RMQHandler.java
- src/main/java/com/ericsson/ei/subscription/RunSubscription.java
The RabbitMQ queue for main consumer is unable to add the binding keys as it returns a List of Binding that is no longer working.
Fixed the above issue with adding a return of Declarables that is consisting of all the bindings. …
> RabbitMQ queue bindings missing due to update in spring boot version

- pom.xml
- src/main/java/com/ericsson/ei/mongo/MongoDBHandler.java
- src/test/java/com/ericsson/ei/mongo/MongoDBHandlerTest.java
It is showing UNAVAILABLE status for mongoDBStatus and eiffelIntelligenceStatus even if connection has been established.
Changed implementation in isMongoDBServerUP method to check status for mongoDB connection.
It will show "AVAILABLE" or "UNAVAILABLE" status based on MongoDB connectivity.
by me, …
> fixed mongodb status issue

- pom.xml
- src/main/java/com/ericsson/ei/subscription/RunSubscription.java
Rather than synchronizing the subscription name, synchronized the current "this" instance.
Resolved the more number of subscription trigger issue at high load.
(c) The …
> Eib more subscription triggering at high load

- pom.xml
To mitigate the vulnerability posed by log4j excluded log4j-to-slf4j dependency
person who certified (a), …
> Excluded log4j-to-slf4j dependency 

- pom.xml
Uplifted the logback-classic dependency version to 1.2.10
person who certified (a), (b) or (c) and I have …
> Uplifted the logback-classic version to 1.2.10

- pom.xml
Bump jackson-databind from 2.13.3 to 2.14.1. …
> Bumps jackson-databind from 2.13.3 to 2.14.1

- wiki/running-eiffel-intelligence.md
Fixes #519 
Documentation improved
Easily understandable by user
person who certified (a), (b) or (c) and I …
> Documention of how run eiffel-intelligence improved

- .github/workflows/main.yml
- jitpack.yml
Configured jitpack with openjdk17
it.
(d) I …
> Configured jitpack with openjdk17

- pom.xml
Uplifted necessary mongo dependencies in EIB for adaptation to MongoDB v6.
Uplifted the following mongo dependencies in EIB for adaptation to MongoDB v6:
1. mongo-driver-core
2. mongo-driver-sync
3. bson
permitted to submit under a different …
> Uplifted necessary mongo dependencies in EIB for adaptation to MongoDB v6

- pom.xml
> Release 3.2.8 Version

- .github/workflows/main.yml
- .mvn/wrapper/maven-wrapper.properties
- jitpack.yml
- mvnw
- mvnw.cmd
Update jitpack configuration to use java temurin distribution
person who certified (a), (b) or (c) and I …
> Update jitpack configuration to use java temurin distribution

- .mvn/maven.config
- README.md
- pom.xml
Update eiffel-commons lib compiled with openjdk distribution
Prepare release for 3.2.10 version
person who …
> Release 3.2.10  with openjdk built eiffel-commons lib

- .github/workflows/main.yml
- pom.xml
Update code coverage with jacoco as cobertura is not compatible with jdk17 …
> Update code coverage with jacoco

- .github/workflows/main.yml
Update api token with project token for codacy in github actions
person who certified (a), (b) or (c) and I …
> Update api token with project token for codacy in github actions

- pom.xml
Update mongo driver to 5.3.0
it.
(d) I …
> Update mongo driver to 5.3.0
