.travis.yml

It seems there is problem with the download URL used by Travis.
link to downloading java 8 in Travis not working
remove requirement to download java 8
None
None
None
(c) …

remove download of java 8

---

src/functionaltests/java/com/ericsson/ei/subscriptions/bulk/SubscriptionBulkSteps.java
src/functionaltests/java/com/ericsson/ei/subscriptions/trigger/SubscriptionTriggerSteps.java
src/functionaltests/resources/subscription_multiple.json
src/main/java/com/ericsson/ei/controller/SubscriptionController.java
src/main/java/com/ericsson/ei/controller/SubscriptionControllerImpl.java
src/main/java/com/ericsson/ei/controller/model/Subscription.java
src/main/java/com/ericsson/ei/repository/ISubscriptionRepository.java
src/main/java/com/ericsson/ei/repository/SubscriptionRepository.java
src/main/java/com/ericsson/ei/services/SubscriptionService.java
src/main/java/com/ericsson/ei/subscriptionhandler/InformSubscription.java
src/main/resources/public/raml/common-schema.raml
src/test/java/com/ericsson/ei/subscriptionhandler/test/SubscriptionHandlerTest.java
src/test/resources/SubscriptionObjectForAuthorization.json
src/test/resources/artifactRequirementSubscription.json
src/test/resources/subscriptionForMapNotification.json

This is related to "Fix auth-behaviour" in EI-frontend and should be merged together.
- There was wierd behaviour regarding the saving of auth information (handling of
username/password since it was used by ldap aswell as the subscription auth)
-If password was not updated from the user request, it would be removed.
- Auth information was sent out to the users in clear text.
- Broke the names for username appart to "ldapUserName" and "userName".
- Made sure mongoDB updates without removing unset fields.
- Made sure password is not sent out to the user by removing that field if it is set.
have the right to submit it under the open …

Fix auth-behaviour

---

pom.xml
src/functionaltests/java/com/ericsson/ei/subscriptions/trigger/SubscriptionTriggerSteps.java
src/main/java/com/ericsson/ei/jmespath/JmesPathInterface.java
src/main/java/com/ericsson/ei/jsonmerge/MergePrepare.java
src/main/java/com/ericsson/ei/waitlist/WaitListWorker.java
src/test/java/com/ericsson/ei/rules/test/TestRulesRestAPI.java

Resending events in waitlist was broken when loaded in Tomcat with other version of JSON library
Changed to jackson json library which will return objects or empty strings and less requirement to have keys in a Json object. Exceptions are no longer thrown but an error message is logged in order to allow processing of coming events in the waitlist to be sent.
None
WaitlistWork less dependent of keys existing or not ad their type.
None
Vasile Baluta, vasile.baluta@ericsson.com

rewrite waitListWorker to be more fail safe

---

pom.xml
src/main/java/com/ericsson/ei/controller/model/ParseInstanceInfoEI.java
src/main/resources/application.properties
src/main/resources/default-application.properties
src/test/java/com/ericsson/ei/rules/test/TestRulesRestAPI.java

Application information such as application name and version is stored in the default-application.properties instead of the application.properties that may be over written by users. This enables us to make use of those values in the front end and display the correct versions.
There is also new fields in the application.properties, build.version.name and =build.version is seperated from the version displayed from the pom, the users may add their own version name if verison is set, if version is set without name then it will be displayed as Enterprise Version in EI front end. …

Fix versions

---

src/main/java/com/ericsson/ei/App.java

It was previously hardcoded to turn off logging if no specific arguments were added when starting up EI backend. When using mvn spring-boot:run the logging was always turned off and overriding the application.properties .
When starting up EI backend it is still possible to specify log level arguments when using the war file.
"java -jar target/eiffel-intelligence-X.X.X.war DEBUG"
If no log levels are passed in as arguments then the application.properties values are used.
Easier to startup EI backend using mvn spring-boot:run
(b) The contribution is …

Removed hard coded log levels

---

wiki/markdown/Query.md

A faulty curl example command was in the documentation.
Corrected and tested the command, which is at the end of the file.  The rest of the changes are code formatting of trailing whitespaces.
Readable. Possible for users to copy + paste and try this command. …

Fix wrong curl command on /query endpoint

---

.travis.yml

We want travis to handle deployment to github pages instead of having to use mvn commands locally before pushing to repo.
A deploy step is added to the travis file. Deployment is only done on master branch. The pages are published to the brnch gh-pages by default. Update repo settings to use gh-pages branch instead of master branch docs/ directory. $GITHUB_TOKEN used in deployment job is set in travis ci settings.
Developer does not have to manually run mvn site and mvn clean to update documentation before commit to repo. Note: whenever documentation is updated in a change it is HIGHLY recommended to test locally!
have the right …

Add travis deploy on pull requests

---

src/functionaltests/java/com/ericsson/ei/notifications/ttl/TestTTLSteps.java
src/functionaltests/resources/features/ttl.feature

Fixed Test TTL for Automatic Subscription Trigger to work in  windows.
Since it was hard to follow one of the test steps as it did three different things I split one step to 3 steps.
Run test using command: `mvn -Dtest=TestTTLRunner test -Dcucumber.options="--tags @TestTTLforAutomaticSubscriptionTrigger"`
Changed all taps to 4 spaces.
work with modifications, …

fix ttl test failed in windows, split test functions

---

src/functionaltests/java/com/ericsson/ei/query/QueryAggregatedObjectsTestSteps.java
src/main/java/com/ericsson/ei/controller/QueryAggregatedObjectControllerImpl.java
src/main/java/com/ericsson/ei/controller/QueryControllerImpl.java

Required for pull request:
https://github.com/eiffel-community/eiffel-intelligence-frontend/pull/143
Intention is to change the check of the "empty" string to a check of the response code which is much cleaner and easier.
When no match is found in query, response code 204 will be returned.
It's easier to detect if the query has failed by simply checking the response code rather than checking the response body.
license and …

Query no content response code is now 204

---

src/functionaltests/java/com/ericsson/ei/subscriptions/crud/SubscriptionCRUDSteps.java
src/functionaltests/resources/features/subscriptionCRUD.feature
src/main/java/com/ericsson/ei/subscriptionhandler/InformSubscriber.java
src/main/java/com/ericsson/ei/subscriptionhandler/SubscriptionValidator.java
src/test/java/com/ericsson/ei/subscriptionhandler/test/SubscriptionHandlerTest.java
src/test/java/com/ericsson/ei/subscriptionhandler/test/SubscriptionValidatorTest.java
src/test/resources/SubscriptionObject.json

Some URL parameters could not be handles as JMESPATH may include invalid characters. This is now handled better so that the JMESPATH expression is not needed to be urlencoded in the notification meta.
The url is encoded before sending it to recieving part although sonce it is impossible to use it if not and if needed.
URL parameters may both be encoded or uncoded since EI will decode if needed the parameters before sending them through the JMESPATH process.
Validation that validated that notification meta was valid has been changed since it declined JMESPATH expressions, now it only validates that it is not empty, and that it is a valid email address if it is a mail notification type. 
(a) The …

URL prameter encoding/decoding added

---

pom.xml

The png files were not copied during site generation, causing the images to not exist in the docs/ directory.
Explicitly telling the resource plugin to include all .png files solves the issue.
Images included in the site documentation, as they should be. …

Fix copy of png files during site generation

---

.travis.yml
pom.xml

We've changed the copy of resources during site generation, and when cleaning the repository the copied images are deleted before site generation.
Removed configuration of the clean plugin. Also removed the mvn clean command from site generation in travis job.
Visible images in the site docs...
by me, …

Removed mvn clean command

---

src/main/docker/Dockerfile
src/main/docker/README.txt
src/main/docker/docker-compose.yml
src/main/docker/health-check.sh
src/main/docker/start-service.sh
wiki/markdown/docker.md

Adding a Dockerfile so user can build Docker image for Docker and Kubernetes.
Make it easy to build Eiffel-Intelligence docker images.
(c) The contribution was provided …

Dockerfile for building images for Docker and Kubernetes

---

.travis.yml

Before the functional tests + integration tests + deployment were done in one big job making it hard to overlook the logs in travis.
* Grouped different tests into separate jobs, one for functional test and one for integration test. They are run in parallel, and get separate logs.
* Set up env for integration tests into before_script (this is only run before ITs and not other jobs)
* Add labels for the different jobs
* Deployment is in it's own stage (moved condition of only running on branch master, to stage condition instead of job level)
* Add comments to steps in travis file
Better overview of travis jobs. Separated logs which makes it easier to troubleshoot if something goes wrong.
(a) The …

Add stages in travis file

---

src/main/java/com/ericsson/ei/services/SubscriptionService.java

When a Subscription is removed, the repeat handler aggregated objects ids should be cleaned.
If a Subscription has never matched any aggregated objects, then no matched aggregated object ids has been stored in database and the clean up of the Subscriptions matched aggregated objects ids produces and error. This error is not a critical error.
The error message has been improved and describe more whats happening.
Log message has been changed to a log warning message instead.
of my …

Fix clean RepeateHandler AggregatedobjectIds log message.

---

.travis.yml
src/functionaltests/java/com/ericsson/ei/subscriptions/repeatHandler/SubscriptionRepeatHandlerSteps.java
src/main/java/com/ericsson/ei/services/SubscriptionService.java
src/main/java/com/ericsson/ei/subscriptionhandler/RunSubscription.java
src/main/java/com/ericsson/ei/subscriptionhandler/SubscriptionRepeatDbHandler.java

This change solves the storing issues of multiple aggregated objects ids in different MongoDb document indexes and multiple of aggregated objects ids for same subscriptions requirements matched aggregated object ids list in RepeatHandler database collection. …

Fixed some of RepeatDBHandling of matched Aggregated Objects ids issues.

---

src/integrationtests/resources/features/ArtifactFlowIT.feature
src/main/resources/schemas/subscription_schema.json

- restPostBodyMediaType was mandatory even with a mail subscription. Now it is only mandatory if you have a REST_POST subscription(That functionality was already implemented).
- Changed test to reflect this.
permitted to submit under a different …

Fix restPostBodyMediaType to not be mandatory in a mail subcription

---

src/main/java/com/ericsson/ei/App.java
src/main/java/com/ericsson/ei/config/CheckEIConfigurations.java
src/main/java/com/ericsson/ei/rules/RulesHandler.java
src/main/resources/application.properties

Today it is really hard to see what rule file that is being used or if EI fails to load Rules file.
Update EI so Rule path is logged and improve logging when Rule path fails to load.
Update so other properties is logged, so its visible which configuration that is being used in the logs.
Password properties is not logged nor printed in console/logs.
work with …

Added Rule File path property and other properties check and logs.

---

src/main/java/com/ericsson/ei/controller/SubscriptionControllerImpl.java
src/main/java/com/ericsson/ei/services/SubscriptionService.java
src/main/java/com/ericsson/ei/subscription/SubscriptionValidator.java
src/test/java/com/ericsson/ei/services/SubscriptionServiceTest.java
src/test/java/com/ericsson/ei/subscription/SubscriptionValidatorTest.java

- A null value when trying to fetch ldapUserName will no longer cause problems
- Implemented test to ensure that null value is handled correctly
- Error handling when failure to delete a subscription is added and should be responded to the user.
- Minor improvement in SubscriptionValidator class that forces the static methods to be called as static methods. …

Fix null point exception deleteing subscription without ldapUserName

---

src/functionaltests/java/com/ericsson/ei/subscriptions/authentication/AuthenticationSteps.java
src/functionaltests/java/com/ericsson/ei/subscriptions/bulk/SubscriptionBulkSteps.java
src/functionaltests/java/com/ericsson/ei/subscriptions/crud/SubscriptionCRUDSteps.java
src/functionaltests/resources/features/subscriptionBulk.feature
src/functionaltests/resources/features/subscriptionCRUD.feature
src/main/java/com/ericsson/ei/controller/AuthControllerImpl.java
src/main/java/com/ericsson/ei/controller/DownloadControllerImpl.java
src/main/java/com/ericsson/ei/controller/InformationControllerImpl.java
src/main/java/com/ericsson/ei/controller/QueryAggregatedObjectController.java
src/main/java/com/ericsson/ei/controller/QueryAggregatedObjectControllerImpl.java
src/main/java/com/ericsson/ei/controller/QueryControllerImpl.java
src/main/java/com/ericsson/ei/controller/QueryMissedNotificationController.java
src/main/java/com/ericsson/ei/controller/QueryMissedNotificationControllerImpl.java
src/main/java/com/ericsson/ei/controller/RuleCheckControllerImpl.java
src/main/java/com/ericsson/ei/controller/SubscriptionController.java
src/main/java/com/ericsson/ei/controller/SubscriptionControllerImpl.java
src/main/java/com/ericsson/ei/utils/ResponseMessage.java
src/main/resources/public/raml/resourceTypes/query-aggregated_object.raml
src/main/resources/public/raml/resourceTypes/query-missed_notifications.raml
src/main/resources/public/raml/resourceTypes/subscription.raml
src/test/java/com/ericsson/ei/services/SubscriptionRestAPITest.java

An attempt to standardize error response. 
- Controllers with strict response types have been made generic to be able to return whatever.
- Error response are returned as a JSON string with a key value pair: {"message":"error"} …

Standardize error message handling

---

src/main/resources/rules/ArtifactRules-Eiffel-Agen-Version.json
src/main/resources/rules/ArtifactRules-Eiffel-Toulouse-Version.json

Aggregated artifact object needs name  from ArtifactNewCreated event.
Change rules for artifact object to aggregate name from ArtifactNewCreated event.
NONE
More flexibility to identify what aggregated artifact objects belong to an ArtifactNewCreated event.
NONE
by me, under the same open source …

extract artifact name into aggregated object

---

src/main/java/com/ericsson/ei/controller/SubscriptionControllerImpl.java
src/main/java/com/ericsson/ei/handlers/MongoDBHandler.java
src/main/java/com/ericsson/ei/notifications/HttpRequestSender.java
src/test/java/com/ericsson/ei/subscription/SubscriptionRepeatDbHandlerTest.java
src/test/resources/logback.xml

Today it has been seen some random, not often, ApplicationContext start issues during tests.
This change is a try to solve that problem and also reduce number exceptions printouts that is printed when embedded mongodb and and embedded messagebus is closed before EI applications has executed finished. …

Reduce and improve logs during test executions

---

pom.xml
src/main/java/com/ericsson/ei/erqueryservice/ERQueryService.java
src/main/java/com/ericsson/ei/erqueryservice/SearchParameters.java
src/main/java/com/ericsson/ei/handlers/ExtractionHandler.java
src/main/java/com/ericsson/ei/handlers/UpStreamEventsHandler.java
src/test/java/com/ericsson/ei/erqueryservice/test/ERQueryServiceTest.java
src/test/java/com/ericsson/ei/flowtests/ArrayAggregationTest.java
src/test/java/com/ericsson/ei/flowtests/FlowSourceChangeObject.java
src/test/java/com/ericsson/ei/flowtests/FlowTest.java
src/test/java/com/ericsson/ei/flowtests/TrafficGeneratedTest.java
src/test/java/com/ericsson/ei/handlers/test/UpStreamEventHandlerTest.java

Needs https://github.com/eiffel-community/eiffel-commons/pull/24 merged and released first.
closes #299
- Fix bug where the URI to ERQueryService was built up incorrect. Changed the rest template to the HttpRequest in Eiffel commons which handles this as well as cleaner code.
- Fix tests to work correctly with new request library. 
work with modifications, …

Fix ERQueryService URI build bug

---

wiki/markdown/subscription-with-REST-POST-notification.md

An old link, pointing to old repository. Still redirects on GitHub...
Updated the link
person who certified …

Fix link pointing to old repository

---

wiki/markdown/compatibility.md

Latest release, 2.0.0 was not included in compatibility page.
Reordered the page so latest releases are on the top of the page. The 2.0.0 release is not backwards compatible with older 1.x versions. Linked to release notes of 2.0.0 release.
Changed the table to be more maintainable in the future, keeping a list of which front-ends are compatible with which back-ends. Keeping the older 1.x versions for now, but for future releases we might want to trim this list a bit.
Latest versions available on this page.
(b) The contribution is based upon …

Add 2.0.0 versions in compatibility page

---

src/main/docker/docker-compose.yml

Noticed there were still some references to gav instead of identity in configuration of indexes for er.
Replaced the gav with identity
Using Agen version for indexes instead of Toulouse. …

Removed gav from database indexes

---

src/functionaltests/java/com/ericsson/ei/query/QueryAggregatedObjectsTestSteps.java
src/test/resources/MissedNotification.json
src/test/resources/MissedNotificationOutput.json

Updated the missed notification test objects so that they look the way they're actually prepared in the InformSubscriber class.
(c) The contribution was provided directly …

Update missed notification test object

---

pom.xml
src/functionaltests/java/com/ericsson/ei/query/QueryAggregatedObjectsTestSteps.java
src/functionaltests/resources/features/queryAggregatedObjects.feature
src/integrationtests/java/com/ericsson/ei/integrationtests/FlowStepsIT.java
src/integrationtests/java/com/ericsson/ei/integrationtests/flow/ArtifactFlowRunnerIT.java
src/integrationtests/java/com/ericsson/ei/integrationtests/flow/FlowStepsIT.java
src/integrationtests/java/com/ericsson/ei/integrationtests/flow/SourceChangeFlowRunnerIT.java
src/integrationtests/java/com/ericsson/ei/integrationtests/flow/TestExecutionRunnerIT.java
src/integrationtests/java/com/ericsson/ei/integrationtests/notification/FailedNotificationRunnerIT.java
src/integrationtests/java/com/ericsson/ei/integrationtests/notification/FailedNotificationStepsIT.java
src/integrationtests/java/util/IntegrationTestBase.java
src/integrationtests/resources/features/ArtifactFlowIT.feature
src/integrationtests/resources/features/FailedNotificationIT.feature
src/integrationtests/resources/features/SourceChangeFlowIT.feature
src/integrationtests/resources/features/TestExecutionFlowIT.feature
src/main/java/com/ericsson/ei/controller/QueryMissedNotificationControllerImpl.java
src/main/java/com/ericsson/ei/notifications/EmailSender.java
src/main/java/com/ericsson/ei/notifications/HttpRequest.java
src/main/java/com/ericsson/ei/notifications/HttpRequestSender.java
src/main/java/com/ericsson/ei/notifications/InformSubscriber.java
src/main/resources/application.properties
src/test/java/com/ericsson/ei/notifications/InformSubscriberTest.java
src/test/java/com/ericsson/ei/queryservice/test/QueryServiceRESTAPITest.java
src/test/resources/MissedNotification.json
src/test/resources/MissedNotificationOutput.json
wiki/markdown/query.md
wiki/markdown/subscription-with-REST-POST-notification.md

https://github.com/eiffel-community/eiffel-intelligence/issues/254
Error message is now part of the failed notification object.
Useful for the failed notifications feature in the front-end. The idea is the be able to see what notification failed and the reason.
by me, under the same open source …

Failed notifications object now stores error message

---

README.md

Removed the REST API listing from the README since it kept being out of sync with the REST-API.md page. …

Remove REST API listing from README

---

pom.xml

Security vulnerability in jackson-databind [CVE-2019-16942](https://nvd.nist.gov/vuln/detail/CVE-2019-16942)
Update the library from 2.9.10 to 2.9.10.1
Avoid security vulnerability
in …

Upgrade jackson-databind from 2.9.10 to 2.9.10.1

---

src/main/java/com/ericsson/ei/controller/model/ParseInstanceInfoEI.java
src/main/java/com/ericsson/ei/utils/SafeLdapServer.java
src/test/java/com/ericsson/ei/utils/SafeLdapServerTest.java

LDAP password was displayed when accessing /information endpoint in EI
/information will now display a safe version of the LDAP settings.
(c) The contribution was …

Fix bug where LDAP password was displayed when fetching EI information

---

src/main/java/com/ericsson/ei/exception/ReplacementMarkerException.java
src/main/java/com/ericsson/ei/rules/MatchIdRulesHandler.java
src/test/java/com/ericsson/ei/extraction/test/TestExtractionHandler.java
src/test/java/com/ericsson/ei/rules/MatchIdRulesHandlerTest.java
src/test/java/com/ericsson/ei/rules/TestIdRulesHandler.java
src/test/java/com/ericsson/ei/rules/TestRulesHandler.java
src/test/java/com/ericsson/ei/rules/TestRulesObject.java
src/test/java/com/ericsson/ei/rules/TestRulesRestAPI.java
src/test/java/com/ericsson/ei/rules/TestRulesService.java
src/test/java/com/ericsson/ei/rules/test/MatchIdRulesHandlerTest.java

We encountered an error with replacement marker mismatch with an unclear error message.
When MatchIdRules does not contain the rules.replacement.marker the error will be clearly logged and an exception will be thrown at that point instead of around 10 steps further in the code.
**Error message:**
"MatchIdRules: {"_id":"%IdentifyRulesEventIds%"} does not contain the rules.replacement.marker: %IdentifyRulesEventId%"
license …

Replacement marker mismatch handled better

---

src/main/java/com/ericsson/ei/handlers/ObjectHandler.java
src/main/java/com/ericsson/ei/handlers/UpStreamEventsHandler.java
src/main/java/com/ericsson/ei/mongo/MongoDBHandler.java
src/main/java/com/ericsson/ei/waitlist/WaitListWorker.java

Fix: https://github.com/eiffel-community/eiffel-intelligence/issues/387
Previously when EI looses connection with mongoDB we will get nullpointer exceptions in several places in the code.
So Handled the NullPointerException by giving proper error log messages and also in some places handled errors by throwing MongoClientException instead of returning null.
Whenever MongoDB goes down, will get error message instead of NullPointerException.
of my knowledge, is covered under an …

Fixed NullPointerException when mongoDB connection goes down

---

.travis.yml
src/main/java/com/ericsson/ei/config/SwaggerConfig.java

Travis configuration showed warnings of deprecation in configuration
SwaggerConfig class contained use of deprecated methods, with SuppressWarning added
* Stop using deprecated constructor in Swagger ApiInfo and introduce Contact
* Remove (useless) sudo in travis configuration and add os tag
Stop using deprecated methods ...
None
work with modifications, …

Remove deprecated methods/annotations in SwaggerConfig and Travis file

---

src/main/java/com/ericsson/ei/controller/model/ParseInstanceInfoEI.java
src/main/java/com/ericsson/ei/erqueryservice/ERQueryService.java
src/main/java/com/ericsson/ei/handlers/DateUtils.java
src/main/java/com/ericsson/ei/handlers/ObjectHandler.java
src/main/java/com/ericsson/ei/handlers/RMQProperties.java
src/main/java/com/ericsson/ei/mongo/MongoCondition.java
src/main/java/com/ericsson/ei/mongo/MongoConstants.java
src/main/java/com/ericsson/ei/mongo/MongoDBHandler.java
src/main/java/com/ericsson/ei/notifications/InformSubscriber.java
src/main/java/com/ericsson/ei/queryservice/ProcessQueryParams.java
src/main/java/com/ericsson/ei/subscription/SubscriptionHandler.java
src/main/java/com/ericsson/ei/waitlist/WaitListStorageHandler.java
src/main/java/com/ericsson/ei/waitlist/WaitListWorker.java
src/test/java/com/ericsson/ei/erqueryservice/test/ERQueryServiceTest.java
src/test/java/com/ericsson/ei/flowtests/SingleEventAggregationTest.java
src/test/java/com/ericsson/ei/handlers/test/ObjectHandlerTest.java
src/test/java/com/ericsson/ei/notifications/InformSubscriberTest.java

/information endpoint returns a json blob containing configuration for Eiffel Intelligence (see in Swagger UI or from command line how this can look like). This JSON model is based on variable names from ParseInstanceInfoEI class which did not reflect the recent changes in application.properties.
* Renamed variables to better match their property names.
* Improved some java doc/spelling here and there ...
* Avoided NullPointerExceptions thrown in SingleEventAggregationTest by setting mock to a value instead of null. In ERQueryService we always expect the response back from ER to contain a body and make no checks for this ... 
* Extracted hard coded values for MongoDB keys to constants in the Mongo package. (I didn't change the "Time" --> "time" key yet, since this also needs documentation …

Improve /information endpoint response

---

src/functionaltests/java/com/ericsson/ei/notifications/trigger/SubscriptionNotificationSteps.java
src/functionaltests/resources/features/subscriptionNotification.feature
src/main/java/com/ericsson/ei/notifications/EmailSender.java
src/test/java/com/ericsson/ei/notifications/EmailSenderTest.java

https://github.com/eiffel-community/eiffel-intelligence/issues/401
Added sender and subject default values for email notification.
We will always have email sender and subject defined, even if users do not defined them in their application.properties.
by me, under the same open source license (unless …

Added default sender and subject values for email notification.

---

pom.xml

Tests are having a very high failure rate.
This little fix splits the surefire plugin into two separate executions. The parallel one runs first with the tests that have no issues running at the same time and the sequential one runs afterwards with tests that are sensitive to parallel execution.
by me, …

Split surefire into a parallel and a sequential execution

---

src/main/java/com/ericsson/ei/queryservice/ProcessAggregatedObject.java

Closes https://github.com/eiffel-community/eiffel-intelligence/issues/441
This is because Eiffel Intelligence doesn't find the resulting aggregation from the database.
The key to search for should be "_id" not "id" - since we can't expect all and every custom rule set to put an "id" in the root of the aggregation.
work with modifications, whether created in …

fix by replacing id with _id

---

src/main/resources/rules/AllEventsRules-Eiffel-Agen-Version.json
src/main/resources/rules/AllEventsRules-Eiffel-Toulouse-Version.json
wiki/example-rules.md

The example rules "All event rules" contained Eiffel events which is not included in the official protocol. And it is not mentioned in the documentation anywhere how the "All event rules" works (compared to the other example rules, these do not define any aggregation of multiple events, but rather stores every event as is). 
Added some clarifying text that the existing example rules called "All events rules", does not actually perform any aggregation on any Eiffel events.
A word of caution is added in the documentation to not use these rules in production for agrgegation purposes.
have the right to submit it under the open source …

Remove non official Eiffel events from all events rules

---

src/functionaltests/java/com/ericsson/ei/rabbitmq/RabbitMQTestConnectionSteps.java
src/functionaltests/java/com/ericsson/ei/rabbitmq/configuration/RabbitMQConfigurationTestRunner.java
src/functionaltests/java/com/ericsson/ei/rabbitmq/configuration/RabbitMQConfigurationTestSteps.java
src/functionaltests/java/com/ericsson/ei/rabbitmq/connection/RabbitMQTestConnectionRunner.java
src/functionaltests/java/com/ericsson/ei/rabbitmq/connection/RabbitMQTestConnectionSteps.java
src/functionaltests/java/com/ericsson/ei/threadingAndWaitlistRepeat/ThreadingAndWaitlistRepeatSteps.java
src/functionaltests/resources/features/rabbitMQConfiguration.feature
src/functionaltests/resources/features/threadingAndWaitlistRepeat.feature
src/main/java/com/ericsson/ei/handlers/RMQHandler.java
src/main/java/com/ericsson/ei/handlers/RMQProperties.java
src/test/java/com/ericsson/ei/handlers/test/RmqPropertiesTest.java
wiki/configuration.md

Closes https://github.com/eiffel-community/eiffel-intelligence/issues/414
Added support for multiple routing key bindings in RabbitMQ. The same rabbitmq.binding.key property is used as a comma separated string e.g. routing-key1, routing-key2.
The internal waitlist will now also publish events using the routing key eiffel-intelligence.waitlist.
This also means that Eiffel Intelligence now listens to events sent using the mentioned routing key.
The waitlist queue is now actually created and internal events are sent on that queue.
This makes it configurable to set up bindings towards several "domains".
have the right to submit it …

Waitlist queue is now created and add support for multiple binding keys

---

src/main/java/com/ericsson/ei/handlers/RmqHandler.java
wiki/markdown/configuration.md

Internal waitlist queue now binds to the exchange using its own name.
That means if the waitlist name is "ei.domain001.my-rules.waitlist" then the binding key will also be that same name.
This is to fix an issue with multiple EI instances listening for events over the same exchange.
With a fixed binding key on all instances they would each get a copy of the event into their waitlist queue even though the event was only meant for one of the queues.
of my knowledge, is covered under …

2.x Use waitlist queue name as routing key

---

src/functionaltests/java/com/ericsson/ei/rabbitmq/connection/RabbitMQTestConnectionSteps.java
src/main/java/com/ericsson/ei/handlers/RMQHandler.java
src/main/java/com/ericsson/ei/handlers/RMQProperties.java
wiki/configuration.md

Internal waitlist queue now binds to the exchange using its own name.
That means if the waitlist name is "ei.domain001.my-rules.waitlist" then the binding key will also be that same name.
This is to fix an issue with multiple EI instances listening for events over the same exchange.
With a fixed binding key on all instances they would each get a copy of the event into their waitlist queue even though the event was only meant for one of the queues.
of my knowledge, is covered under …

3.x Use waitlist queue name as routing key

---

pom.xml
src/main/java/com/ericsson/ei/controller/model/ParseInstanceInfoEI.java

- Added default values for subsciption thread handling in
ParseInstanceInfo class
- Updated pom.xml file with a new version
After the fix for subscription thread, if the default values are not provided in the application.properties the EI backed fails to start because of the missing default values in ParseInstanceInfo class.
Added default values in the ParseInstanceInfo class so that the application can start even without providing the subscription-thread.* values in applicaion.properties.
SignedBy : @SantoshNC68 
(b) The contribution is based upon …

Added default values in ParseInstanceInfo class for subscription

---

pom.xml
src/functionaltests/java/com/ericsson/ei/rabbitmq/configuration/RabbitMQConfigurationTestSteps.java
src/functionaltests/java/com/ericsson/ei/rabbitmq/connection/RabbitMQTestConnectionSteps.java
src/functionaltests/resources/features/rabbitMQConfiguration.feature
src/functionaltests/resources/features/rabbitMQTestConnection.feature
src/main/java/com/ericsson/ei/handlers/RmqHandler.java
src/main/resources/application.properties
src/test/java/com/ericsson/ei/handlers/test/RmqHandlerTest.java
wiki/markdown/configuration.md

If binding key is changed in configuration, the old bindingkey is removed from mb queue.
Reduction in conflicts between the binding keys.
(c) The contribution was …

Old bindingkey is removed if binding key is changed in configuration

---

src/functionaltests/java/com/ericsson/ei/utils/DataBaseManager.java
src/main/java/com/ericsson/ei/handlers/EventToObjectMapHandler.java
src/main/java/com/ericsson/ei/handlers/MongoDBHandler.java
src/main/java/com/ericsson/ei/jmespath/JmesPathInterface.java
src/main/java/com/ericsson/ei/jsonmerge/MergeHandler.java
src/main/java/com/ericsson/ei/waitlist/WaitListStorageHandler.java
src/main/resources/application.properties
src/test/java/com/ericsson/ei/handlers/test/MongoDBHandlerTest.java

NA
Made code changes to handle the updation of events in Object to Event mapper.
Also updated the logic to not store duplicate eventIds.
Performance improvements in storing the ObjectToEvent mapping relation without having to query multiple times. …

Fix for MongoDBHandling on ObjectToEvent map handling

---

pom.xml
src/main/java/com/ericsson/ei/notifications/JenkinsCrumb.java
src/main/java/com/ericsson/ei/notifications/UrlParser.java
src/test/java/com/ericsson/ei/notifications/JenkinsCrumbTest.java

The jenkins jobs were not getting triggered as part of jenkins version uplift(2.222.3), which involves CSRF protection using jenkins crumbs.
The rest url post requests were getting failed because of invalid crumb request, so changed the url parsing and added the context path(/jenkins).
by me, under …

EIB: Jenkins job not getting triggered after version uplift to 2.222.3

---

src/main/java/com/ericsson/ei/handlers/ObjectHandler.java

This fix for duplication of ttl fields in Information RestApi.
Old and faulty "/information" entrypoint return value:
"objectHandler": {
"collectionName": "aggregated_objects",
"databaseName": "eiffel_intelligence",
"ttlValue": "",
"ttl": 0
},
With this PR change, which is how it should be:
"objectHandler": {
"collectionName": "aggregated_objects",
"databaseName": "eiffel_intelligence",
"ttlValue": ""
},
license and I have …

Removed the duplication of Ttl fields in /Infromation RestApi

---

pom.xml
src/main/java/com/ericsson/ei/notifications/JenkinsCrumb.java
src/main/java/com/ericsson/ei/notifications/UrlParser.java
src/test/java/com/ericsson/ei/notifications/JenkinsCrumbTest.java

With jenkins uplift to 2.222.3, we have CSRF protection which needs crumbs to make rest post calls to jenkins.
The crumb issuer end point is not working which will be hitted when BASIC_AUTH_CSRF_PROTECTION is the AUTH_TYPE
for the subscrptions to trigger the jenkins jobs. Due to this the jenkins obs are not getting triggered. 
Made the code change that triggers the jenkins jobs for the subscrptions for AUTH_TYPE "BASIC_AUTH_CSRF_PROTECTION"
of my knowledge, is covered under an …

EIB: Jenkibs job not getting triggered after jenkins uplift to 2.222.3

---

src/functionaltests/java/com/ericsson/ei/notifications/ttl/TestTTLSteps.java
src/main/java/com/ericsson/ei/controller/RuleControllerImpl.java
src/main/java/com/ericsson/ei/exception/MongoDBConnectionException.java
src/main/java/com/ericsson/ei/handlers/DownstreamIdRulesHandler.java
src/main/java/com/ericsson/ei/handlers/EventHandler.java
src/main/java/com/ericsson/ei/handlers/ExtractionHandler.java
src/main/java/com/ericsson/ei/handlers/IdRulesHandler.java
src/main/java/com/ericsson/ei/handlers/MongoDBHandler.java
src/main/java/com/ericsson/ei/handlers/ObjectHandler.java
src/main/java/com/ericsson/ei/jsonmerge/MergeHandler.java
src/main/java/com/ericsson/ei/notifications/InformSubscriber.java
src/main/java/com/ericsson/ei/services/IRuleCheckService.java
src/main/java/com/ericsson/ei/services/RuleCheckService.java
src/main/java/com/ericsson/ei/utils/MongoDBMonitorThread.java
src/main/java/com/ericsson/ei/waitlist/WaitListStorageHandler.java
src/test/java/com/ericsson/ei/handlers/test/MongoDBHandlerTest.java

Provided the fix for handling the long message queue issue when the mongoDB connection is down.
As a part of this implementation,  during the events publishing if the MongDB is down, a monitor thread will start and it will check DB connection status for every 30 seconds once the DB connection is up events will starts for consuming
Queued events will be redelivered once the mongoDB connection is Re-established. 
No need to restart the EI-backend component
of my knowledge, is covered …

events are not processing from queue

---

src/main/java/com/ericsson/ei/handlers/ObjectHandler.java
src/main/java/com/ericsson/ei/mongo/MongoDBHandler.java
src/main/java/com/ericsson/ei/subscription/SubscriptionHandler.java
src/main/resources/application.properties

Today EI consume a lot of CPU and Memory reasources due to EI can consume a lot events that causes spawning a lot of threads that causes high JVM CPU and Memory load.
Since each thread has also has a MongoDB connector, it will cause high load on MongoDB as well.
In some deployments it has been reported that EI consumes to much resource(CPU, memory) and this due to that we use unlimited number of threads for matching aggregations with subscriptions jmePaths and in same time a lot of MongoDB queries is made from these threads, which causes extra load on MongoDb.
With this change only one and same thread that consumes the event from MessageBus is used through whole EI.
By doing this, we avoid using too much memory and too much CPU.
If the system that is used can handle more events and …

Change Event and Aggreagations threads to use only one threadpool

---

src/integrationtests/resources/application.properties
src/main/java/com/ericsson/ei/erqueryservice/ERQueryService.java
src/main/resources/application.properties
src/test/java/com/ericsson/ei/erqueryservice/test/ERQueryServiceTest.java
wiki/configuration.md

Implemented changes for shallow behavior in EIB
Providing shallow parameter as true by default in EI-Backend , will limit the ER query from EIB to search for upstream/downstream events in main ER only. Search will not be navigated to external ER(s). Configurable parameter **event.repository.shallow** added in application.properties to support these changes. …

Implemented changes for shallow behavior in EIB

---

pom.xml
src/main/java/com/ericsson/ei/notifications/HttpRequestSender.java
src/main/resources/application.properties
wiki/configuration.md

Implementation is done to handle EI Frontend clogged when old subscriptions are not removed.
When the REST Endpoints are unresponsive the subscriptions are blocked by it (currently it takes around 2 mins to check the response and retry) and the application eventually becomes unresponsive.
To avoid this we have introduced a timeout value which can be configured using the application properties instead of depending on http default values
EI Frontend has a customized timeout from which we can get fast responses from the Rest Post notifications when a subscription is triggered. …

EI Frontend clogged when old subscriptions are not removed.

---

pom.xml
src/main/java/com/ericsson/ei/handlers/EventToObjectMapHandler.java
src/main/java/com/ericsson/ei/mongo/MongoDBHandler.java
src/test/java/com/ericsson/ei/mongo/MongoDBHandlerTest.java

Missing entries in event-to-object map collection due to duplicate key error in event-to-object map collection
Provided fix using exception handling with updating of event-to-object map collection in case of duplicate key insertion.
It will update event-to-object map collection in case of duplicate key insertion error.
work with modifications, whether created …

Duplicate key error fix

---

wiki/triggering-jenkins-jobs.md

Subscription notification getting missed for Jenkins job trigger due to 403 invalid crumb exception.
Updated documentation with below details.
As improved CSRF protection provided since Jenkins version 2.176.2, it is recommended that to set this Password/Token field as an API token and not Jenkins user password.
It will provide improved CSRF protection to trigger Jenkins job by subscription notification.
Improved CSRF protection provided since Jenkins version 2.176.2, there are chances of subscription notifications getting missed with 403 exception due to session id check in case of Jenkins user password used in subscriptions. …

EI Documentation update regarding API Token usage in Jenkins authentication for subscription

---

.travis.yml
pom.xml
src/functionaltests/java/com/ericsson/ei/encryption/EncryptionSteps.java
src/functionaltests/java/com/ericsson/ei/encryption/TestEncryptionRunner.java
src/functionaltests/java/com/ericsson/ei/notifications/trigger/SubscriptionNotificationSteps.java
src/functionaltests/java/com/ericsson/ei/notifications/ttl/TestTTLSteps.java
src/functionaltests/java/com/ericsson/ei/query/QueryAggregatedObjectsTestSteps.java
src/functionaltests/java/com/ericsson/ei/utils/TestLDAPStarter.java
src/functionaltests/resources/application.properties
src/functionaltests/resources/features/subscriptionNotification.feature
src/main/java/com/ericsson/ei/controller/RuleTestControllerImpl.java

Fixed testcase failures

---

pom.xml
src/functionaltests/resources/application.properties
src/integrationtests/resources/application.properties
src/main/java/com/ericsson/ei/config/SpringAsyncConfig.java
src/main/java/com/ericsson/ei/controller/model/ParseInstanceInfoEI.java
src/main/resources/application.properties

committed changes for springboot uplift 2.7.5

---

.github/workflows/main.yml

Update github actions with codacy api token …

Update github actions with codacy api token
